mode:
  develop: true

server:
  port: 8080

log:
  MaxSize: 1 #日志文件最大尺寸（M）
  MaxBackups: 10 #保留就文件最大个数
  MaxAge: 90 #保留旧文件最大天数

db:
  dsn: root:abc@tcp(127.0.0.1:3306)/goweb?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 #最多空闲连接数
  maxOpenConn: 10 #最大打开连接数

redis:
  url: localhost:6379

jwt:
  tokenExpire: 3 #token有效时长分钟
  signingKey: gogofly
