info:
  contact: {}
  description: gogoFly!
  title: go-Web
  version: 0.0.1
paths:
  /api/v1/public/user/login:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 登陆成功
          schema:
            type: string
        "401":
          description: 登陆失败
          schema:
            type: string
      summary: user login
swagger: "2.0"
